services:
  frontend:
    image: yourdockerhubuser/seattle-transit-sim-frontend:latest
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    image: yourdockerhubuser/seattle-transit-sim-backend:latest
    build:
      context: .
      dockerfile: backend.Dockerfile
